version: "3.9"

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: home_chore_bot
    environment:
      - TELEGRAM_BOT_TOKEN=your_telegram_bot_token_here
      - TELEGRAM_CHAT_IDS=1234567890,0987654321
    restart: unless-stopped
